spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:mem:testDb'
#    url: 'jdbc:mysql://localhost:3306/testOps'
#    username: 'root'
  jpa:
    hibernate:
      ddl-auto: create-drop

